---
title: "First excercise pt1"
author: "202404927"
date: "October 2024"
output: firstexercise.html
---

## Transforming data - function 1

We first import our libraries and install the package that will allow us to read the excel.

```{r}
library("tidyverse")
library(readxl)
```

After we import our database, we create our function that will transform our data by removing any rows that contain blank spaces.

```{r}
data <- read_excel("/Users/ceciliag/MY472-Local/practicerepo/vehicular-accidents-monterrey.xlsx", sheet = "Feuil1") 

transform_data_1 <- function(data) { 
  transformed_data <- data[complete.cases(data), ] #We remove the rows with blank spaces return(transformed)
  return(transform_data_1)
} 

```

## Transforming data - function 2

```{r}
data_new <- read_excel("/Users/ceciliag/MY472-Local/practicerepo/vehicular-accidents-monterrey.xlsx", sheet = "Feuil1") 

transform_data_n2 <- function(data_new) {
    transformed_data_2 <- data[data$ejercicio > 2023, ]  # Filter rows where the year of the accidents reported is 2023
    return(transformed_data_2)
}


```
